// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqkecqvfqbbhbvnaokmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxa2VjcXZmcWJiaGJ2bmFva21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODg1MDgsImV4cCI6MjA1NzM2NDUwOH0.36HYJbGbwircqp8zyl0jJz5cxuwctQtAhDcUr0CtoNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);